<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CinemaTests\CinemaTests.csproj" />
    <ProjectReference Include="..\CustomThreadPoolLib\CustomThreadPoolLib.csproj" />
    <ProjectReference Include="..\MyTestingLibrary\TestingLibrary.csproj" />
  </ItemGroup>

</Project>
